project:
  type: website

website:
  title: "Stepping Stones"
  site-url: ""
  favicon: "images/posit-favicon.svg"
  open-graph: true
  page-navigation: false
  navbar:
    pinned: true
    logo: images/posit-logo-fullcolor-TM.png
    logo-alt: "Posit logo."
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true
    link-external-newwindow: true
    link-external-icon: true
    number-sections: false
    footnotes-hover: true
    theme:
      - cosmo
      - styles.scss
    fontsize: 16px
    code-overflow: scroll
    code-copy: true

editor: visual

